### ISSUE TITLE
TopicARN

### ISSUE THREAD

**Issue by SaudTauqeer** [blueimp/aws-lambda#11]
Hi, I have followed all the steps and so far I have been able to successfully send notifications using test data.
However, it's not triggering on actual EB instance triggers.
What I have done so far:
- Tested the lamba function with dummy data (its sending notifications).
- Created an SNS topic and subscription and for the protocol, I put in the lamba function ARN.
I believe I'm failing to properly do the final step:
```
Add the Topic ARN as Notification setting to your Elastic Beanstalk environment configuration:
```
At the root of the project I have the config setup like this:
https://jmp.sh/BWEDzFA
and the config contains this:
```
option_settings:
  aws:elasticbeanstalk:sns:topics:
    # Send deployment and health notifications to this Amazon SNS topic:
    NotificationTopicARN: arn:aws:sns:us-east-1:554436049797:draftxr-eb-slack-notifs
```
Thank you for building this tool. Saved me a ton of time writing it from scratch. Looking forward hearing back from you.

**Comment by blueimp** [comment]
Hi @SaudTauqeer ,
I've updated (6901c04d35692f5ea418137b757530f338c6cec8) the [documentation](https://github.com/blueimp/aws-lambda/tree/master/elastic-beanstalk-events-to-slack#trigger-configuration) on where exactly the Topic ARN can be set.

The provided code sample has to be added to your [Elastic Beanstalk Environment Manifest (env.yaml)](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-manifest.html):
```yaml
OptionSettings:
  aws:elasticbeanstalk:sns:topics:
    # Send deployment and health notifications to this Amazon SNS topic:
    NotificationTopicARN: arn:aws:sns:eu-west-1:000000000000:eb-deployments
```

If you want to add this configuration via [ebextensions](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html) instead, you have to use a different YAML syntax for the [option settings](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions-optionsettings.html):
```yaml
option_settings:
  - namespace:  aws:elasticbeanstalk:sns:topics
    option_name:  NotificationTopicARN
    value:  arn:aws:sns:eu-west-1:000000000000:eb-deployments
```
I haven't tested the setting via ebextensions, but based on the documentation I believe this to be the correct syntax.
